const products = [
    {
      id: 1,
      name: "Fennel",
      category: "Bulbs",
      price: 2.5,
      imageUrl: "https://m.media-amazon.com/images/I/81d52532TiL._SL1200_.jpg",
      description: "A flavorful bulb with feathery leaves, often used in salads and soups.",
    },
    {
      id: 2,
      name: "Garlic",
      category: "Bulbs",
      price: 0.75,
      imageUrl: "https://m.media-amazon.com/images/I/610xTQIGeSL.jpg",
      description: "A pungent bulb used to add flavor to a variety of dishes.",
    },
    {
      id: 3,
      name: "Broccoli",
      category: "Flowers",
      price: 2.0,
      imageUrl: "https://media.healthyfood.com/wp-content/uploads/2017/03/What_to_do_with_broccoli-1.jpg",
      description: "A healthy and fibrous vegetable that is great steamed or in salads.",
    },
    {
      id: 4,
      name: "Cauliflower",
      category: "Flowers",
      price: 2.0,
      imageUrl: "https://m.media-amazon.com/images/I/51BomV2ZiaL.jpg",
      description: "A versatile vegetable that can be roasted, steamed, or used as a low-carb substitute.",
    },
    {
      id: 5,
      name: "Tomato",
      category: "Fruits",
      price: 1.1,
      imageUrl: "https://m.media-amazon.com/images/I/61ZJhcdG7LL._SL1500_.jpg",
      description: "A juicy and tangy fruit often used as a vegetable in salads and cooking.",
    },
    {
      id: 6,
      name: "Eggplant",
      category: "Fruits",
      price: 1.5,
      imageUrl: "https://m.media-amazon.com/images/I/41+Ihn6UTLL.jpg",
      description: "A versatile fruit that can be grilled, roasted, or used in a variety of dishes.",
    },
    {
      id: 7,
      name: "Mushroom",
      category: "Fungi",
      price: 2.5,
      imageUrl: "https://m.media-amazon.com/images/I/71XMKwfQCzL._SL1500_.jpg",
      description: "An edible fungus that adds a rich, umami flavor to dishes.",
    },
    {
      id: 8,
      name: "Spinach",
      category: "Leaves",
      price: 1.25,
      imageUrl: "https://m.media-amazon.com/images/I/71J4gpncRhL._SL1500_.jpg",
      description: "A leafy green vegetable that is rich in iron and vitamins.",
    },
    {
      id: 9,
      name: "Lettuce",
      category: "Leaves",
      price: 1.0,
      imageUrl: "https://m.media-amazon.com/images/I/81TGk89l2UL._SL1500_.jpg",
      description: "A crunchy green leafy vegetable commonly used in salads.",
    },
    {
      id: 10,
      name: "Carrot",
      category: "Roots",
      price: 0.75,
      imageUrl: "https://m.media-amazon.com/images/I/81weI2ULFYL._SL1500_.jpg",
      description: "A crunchy and sweet root vegetable that is great for your eyes.",
    },
    {
      id: 11,
      name: "Radish",
      category: "Roots",
      price: 1.0,
      imageUrl: "https://freshji.in/wp-content/uploads/2020/09/Radish-1.jpg",
      description: "A spicy and crunchy root vegetable often used in salads.",
    },
    {
      id: 12,
      name: "Green Bean",
      category: "Seeds",
      price: 1.5,
      imageUrl: "https://m.media-amazon.com/images/I/71LdDyAJtmL._SL1500_.jpg",
      description: "A crisp and tender vegetable that is great steamed or in stir-fries.",
    },
    {
      id: 13,
      name: "Pea",
      category: "Seeds",
      price: 1.5,
      imageUrl: "https://m.media-amazon.com/images/I/71EttZ0FwHL._SL1500_.jpg",
      description: "A sweet and tender legume often used in soups and salads.",
    },
    {
      id: 14,
      name: "Asparagus",
      category: "Stems",
      price: 2.5,
      imageUrl: "https://m.media-amazon.com/images/I/61b6-TZUJzL.jpg",
      description: "A tender and flavorful stem vegetable that is great grilled or steamed.",
    },
    {
      id: 15,
      name: "Celery",
      category: "Stems",
      price: 1.2,
      imageUrl: "https://m.media-amazon.com/images/I/41-boo6FQ9L.jpg",
      description: "A crunchy and refreshing stem vegetable often used in salads and soups.",
    },
    {
      id: 16,
      name: "Potato",
      category: "Tubers",
      price: 0.6,
      imageUrl: "https://m.media-amazon.com/images/I/313dtY-LOEL.jpg",
      description: "A versatile and starchy vegetable that can be baked, boiled, or fried.",
    }
  ];
  
  export default products;
  